<?php
	if(!isset($_SESSION))
		session_start();
		unset($_SESSION["success"]);
		unset($_SESSION["user"]);
		unset($_SESSION["hotenadmin"]);
		unset($_SESSION["quyenhan"]);
		header("location:login.php");
		session_destroy();
?>